// ─── Shared data for all Home section components ───────────────────────────

export const HERO_SLIDES = [
  {
    id: 0,
    name: "Air Velocity Pro",
    tagline: "Born to Break Records",
    sub: "Ultra-light foam sole · 360° knit upper · Carbon fiber plate",
    price: "$189",
    oldPrice: "$240",
    tag: "Best Seller",
    image: "/shoes3.webp",
    thumb: "/shoes3.webp",
    bg: "from-[#ff4d00] via-[#1a0800] to-[#0a0a0f]",
    glow: "rgba(255,100,0,0.55)",
    accent: "#ff6a00",
    dotColor: "bg-orange-500",
    size: "US 7 – 13",
  },
  {
    id: 1,
    name: "Shadow Runner X",
    tagline: "Streets Are Your Runway",
    sub: "Suede & mesh blend · Cushion Cloud™ insole · Reflective trim",
    price: "$159",
    oldPrice: "$200",
    tag: "New Drop",
    image: "shoes4.png",
    thumb: "shoes4.png",
    bg: "from-[#6d00ff] via-[#0d001a] to-[#0a0a0f]",
    glow: "rgba(120,0,255,0.55)",
    accent: "#9f7aea",
    dotColor: "bg-violet-500",
    size: "US 5 – 11",
  },
  {
    id: 2,
    name: "Terra Grip Elite",
    tagline: "Conquer Every Terrain",
    sub: "Vibram outsole · Gore-Tex lining · Quick-dry mesh collar",
    price: "$219",
    oldPrice: "$280",
    tag: "Limited",
    image: "shoes5.png",
    thumb: "shoes5.png",
    bg: "from-[#00a86b] via-[#001a0d] to-[#0a0a0f]",
    glow: "rgba(0,200,100,0.45)",
    accent: "#10b981",
    dotColor: "bg-emerald-500",
    size: "US 6 – 14",
  },
  {
    id: 3,
    name: "Neon Dash Classic",
    tagline: "Pure Energy. Pure Style.",
    sub: "Memory foam insole · Neon contrast sole · Breathable mesh",
    price: "$139",
    oldPrice: "$175",
    tag: "🔥 Hot",
    image: "/image8.png",
    thumb: "/image8.png",
    bg: "from-[#e91e8c] via-[#1a0010] to-[#0a0a0f]",
    glow: "rgba(233,30,140,0.5)",
    accent: "#ec4899",
    dotColor: "bg-pink-500",
    size: "US 6 – 13",
  },
];

export const SLIDE_DURATION = 4500;

export const FEATURED = [
  {
    id: 1,
    slug: "air-velocity-pro",
    name: "Air Velocity Pro",
    price: "$189",
    oldPrice: "$240",
    tag: "Best Seller",
    category: "Running",
    color: "from-orange-500 to-red-600",
    accent: "#ff6a00",
    glow: "rgba(255,106,0,0.4)",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop&sat=-50",
      "https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=90&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: 2341,
    sizes: ["US 7","US 8","US 9","US 10","US 11","US 12","US 13"],
    description: "Engineered for elite performance, the Air Velocity Pro features a carbon fiber plate and 360° knit upper for maximum energy return. Whether you're hitting a marathon PR or dominating the track, these shoes deliver.",
    features: ["Carbon fiber plate", "360° knit upper", "Ultra-light foam sole", "Reflective trim", "Breathable mesh collar"],
    badge: "🏆",
  },
  {
    id: 2,
    slug: "shadow-runner-x",
    name: "Shadow Runner X",
    price: "$159",
    oldPrice: "$200",
    tag: "New Drop",
    category: "Lifestyle",
    color: "from-violet-600 to-indigo-700",
    accent: "#9f7aea",
    glow: "rgba(159,122,234,0.4)",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=90&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: 1820,
    sizes: ["US 5","US 6","US 7","US 8","US 9","US 10","US 11"],
    description: "Street-ready from day one. The Shadow Runner X blends suede craftsmanship with next-gen cushioning for an unbeatable lifestyle shoe that turns heads from morning to midnight.",
    features: ["Suede & mesh blend", "Cushion Cloud™ insole", "Reflective trim", "Dual-density midsole", "Pull-tab heel"],
    badge: "✨",
  },
  {
    id: 3,
    slug: "terra-grip-elite",
    name: "Terra Grip Elite",
    price: "$219",
    oldPrice: "$280",
    tag: "Limited",
    category: "Trail",
    color: "from-emerald-500 to-teal-700",
    accent: "#10b981",
    glow: "rgba(16,185,129,0.4)",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=90&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=90&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: 987,
    sizes: ["US 6","US 7","US 8","US 9","US 10","US 11","US 12","US 13","US 14"],
    description: "Built for those who conquer terrain, not avoid it. The Terra Grip Elite pairs Vibram's legendary outsole with Gore-Tex waterproofing — mud, streams, and rocky ridges are just obstacles in your way.",
    features: ["Vibram outsole", "Gore-Tex lining", "Quick-dry mesh collar", "Rock plate protection", "Heel cage support"],
    badge: "🌿",
  },
  {
    id: 4,
    slug: "neon-dash-classic",
    name: "Neon Dash Classic",
    price: "$139",
    oldPrice: "$175",
    tag: "Hot",
    category: "Lifestyle",
    color: "from-pink-500 to-rose-600",
    accent: "#ec4899",
    glow: "rgba(236,72,153,0.4)",
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=90&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=90&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: 3102,
    sizes: ["US 6","US 7","US 8","US 9","US 10","US 11","US 12","US 13"],
    description: "Pure energy in every step. The Neon Dash Classic brings vivid colourways, memory-foam comfort and a neon contrast sole that makes a statement without sacrificing a single step of performance.",
    features: ["Memory foam insole", "Neon contrast sole", "Breathable mesh upper", "Padded ankle collar", "Lightweight EVA midsole"],
    badge: "⚡",
  },
];

export const CATEGORIES = [
  { label: "Running",    icon: "running",    count: "240+ styles" },
  { label: "Basketball", icon: "basketball", count: "180+ styles" },
  { label: "Lifestyle",  icon: "lifestyle",  count: "320+ styles" },
  { label: "Trail",      icon: "trail",      count: "150+ styles" },
  { label: "Formal",     icon: "formal",     count: "90+ styles"  },
  { label: "Kids",       icon: "kids",       count: "200+ styles" },
];

export const BRANDS = [
  { name: "Nike",        tag: "Just Do It",              logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",                                                          products: 142 },
  { name: "Adidas",      tag: "Impossible Is Nothing",   logoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",                                                        products: 118 },
  { name: "Puma",        tag: "Forever Faster",          logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Puma_logo.svg/2560px-Puma_logo.svg.png",                           products: 87  },
  { name: "New Balance", tag: "Fearlessly Independent",  logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/New_Balance_logo.svg/2560px-New_Balance_logo.svg.png",             products: 96  },
  { name: "Reebok",      tag: "Be More Human",           logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Reebok_2019_logo.svg/2560px-Reebok_2019_logo.svg.png",             products: 73  },
  { name: "Converse",    tag: "Made by You",             logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Converse_logo.svg/2560px-Converse_logo.svg.png",                   products: 65  },
  { name: "Vans",        tag: "Off the Wall",            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Vans-logo.svg/2560px-Vans-logo.svg.png",                           products: 81  },
  { name: "Jordan",      tag: "Wings for the Future",    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Jumpman_logo.svg/1024px-Jumpman_logo.svg.png",                          products: 54  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah K.",
    role: "Marathon Runner",
    avatar: "SK",
    avatarBg: "from-orange-500 to-red-500",
    text: "The Air Velocity Pro literally changed how I run. 42km and my feet still feel amazing. Best investment I've made for my training.",
    rating: 5,
    product: "Air Velocity Pro",
    location: "New York, US",
    verified: true,
  },
  {
    name: "Marcus T.",
    role: "Street Photographer",
    avatar: "MT",
    avatarBg: "from-violet-500 to-indigo-600",
    text: "Style meets comfort like never before. I wear my Shadow Runners to every shoot — they keep up with me from dawn to midnight.",
    rating: 5,
    product: "Shadow Runner X",
    location: "London, UK",
    verified: true,
  },
  {
    name: "Priya M.",
    role: "Fitness Coach",
    avatar: "PM",
    avatarBg: "from-pink-500 to-rose-500",
    text: "I recommend Emirates Shoes to all my clients. The quality-to-price ratio is unmatched. My whole gym class switched over.",
    rating: 5,
    product: "Terra Grip Elite",
    location: "Dubai, UAE",
    verified: true,
  },
  {
    name: "Jordan L.",
    role: "NBA Trainee",
    avatar: "JL",
    avatarBg: "from-blue-500 to-cyan-500",
    text: "Court grip is insane. I've tried every brand and nothing holds a candle to how responsive these feel on hardwood.",
    rating: 5,
    product: "Air Velocity Pro",
    location: "Chicago, US",
    verified: true,
  },
  {
    name: "Aisha R.",
    role: "Travel Blogger",
    avatar: "AR",
    avatarBg: "from-emerald-500 to-teal-500",
    text: "Walked 30,000 steps across Tokyo in these. Zero blisters, zero complaints. They're the only shoes in my luggage now.",
    rating: 5,
    product: "Neon Dash Classic",
    location: "Tokyo, JP",
    verified: true,
  },
  {
    name: "Tyler B.",
    role: "Trail Runner",
    avatar: "TB",
    avatarBg: "from-yellow-500 to-orange-500",
    text: "The Terra Grip Elite handled mud, rocks and river crossings on my last ultra. Came out looking brand new. Absolutely wild.",
    rating: 5,
    product: "Terra Grip Elite",
    location: "Vancouver, CA",
    verified: true,
  },
];

export const SOCIAL_POSTS = [
  { bg: "from-orange-600 to-red-700",   e: "👟", handle: "@mike_runs"   },
  { bg: "from-violet-600 to-indigo-700", e: "👠", handle: "@streetstyle" },
  { bg: "from-emerald-500 to-teal-700",  e: "🥾", handle: "@trail_emma"  },
  { bg: "from-pink-500 to-rose-600",     e: "👟", handle: "@neon_vibes"  },
  { bg: "from-blue-500 to-cyan-600",     e: "🩴", handle: "@beachwalks"  },
  { bg: "from-yellow-500 to-orange-600", e: "👞", handle: "@daily_kicks" },
];
